export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST";
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const LOGS_REQUEST = "LOGS_REQUEST";
export const LOGS_SUCCESS = "LOGS_SUCCESS";
export const LOGS_FAIL = "LOGS_FAIL";